export const ListSalary = [
  {
    salaryCompositionId: 1,
    salaryCompositionCode: "CMP001",
    salaryCompositionName: "Lương cơ bản",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Salary",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 8000000,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 2,
    salaryCompositionCode: "CMP002",
    salaryCompositionName: "Phụ cấp ăn trưa",
    OrganizationUnitData: "Phòng Kinh doanh",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 500000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 3,
    salaryCompositionCode: "CMP003",
    salaryCompositionName: "Phụ cấp đi lại",
    OrganizationUnitData: "Phòng Kế toán",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 700000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 4,
    salaryCompositionCode: "CMP004",
    salaryCompositionName: "Thưởng doanh số",
    OrganizationUnitData: "Phòng Kinh doanh",
    componentType: "Bonus",
    nature: "Positive",
    salaryValueType: "Percentage",
    salaryValue: 5,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 5,
    salaryCompositionCode: "CMP005",
    salaryCompositionName: "Thưởng chuyên cần",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Bonus",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 300000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 6,
    salaryCompositionCode: "CMP006",
    salaryCompositionName: "Bảo hiểm xã hội",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Insurance",
    nature: "Negative",
    salaryValueType: "Percentage",
    salaryValue: 8,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 7,
    salaryCompositionCode: "CMP007",
    salaryCompositionName: "Bảo hiểm y tế",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Insurance",
    nature: "Negative",
    salaryValueType: "Percentage",
    salaryValue: 1.5,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 8,
    salaryCompositionCode: "CMP008",
    salaryCompositionName: "Bảo hiểm thất nghiệp",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Insurance",
    nature: "Negative",
    salaryValueType: "Percentage",
    salaryValue: 1,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 9,
    salaryCompositionCode: "CMP009",
    salaryCompositionName: "Khấu trừ công đoàn",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Deduction",
    nature: "Negative",
    salaryValueType: "Fixed",
    salaryValue: 50000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 10,
    salaryCompositionCode: "CMP010",
    salaryCompositionName: "Lương tăng ca",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Salary",
    nature: "Positive",
    salaryValueType: "Formula",
    salaryValue: "hours * rate * 150%",
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 11,
    salaryCompositionCode: "CMP011",
    salaryCompositionName: "Phí giữ xe",
    OrganizationUnitData: "Phòng Kỹ thuật",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 120000,
    source: "User",
    status: "Inactive",
  },
  {
    salaryCompositionId: 12,
    salaryCompositionCode: "CMP012",
    salaryCompositionName: "Thưởng dự án",
    OrganizationUnitData: "Phòng IT",
    componentType: "Bonus",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 1500000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 13,
    salaryCompositionCode: "CMP013",
    salaryCompositionName: "Hoa hồng bán hàng",
    OrganizationUnitData: "Phòng Kinh doanh",
    componentType: "Commission",
    nature: "Positive",
    salaryValueType: "Percentage",
    salaryValue: 2,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 14,
    salaryCompositionCode: "CMP014",
    salaryCompositionName: "Khấu trừ đi muộn",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Deduction",
    nature: "Negative",
    salaryValueType: "Formula",
    salaryValue: "lateMinutes * 5000",
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 15,
    salaryCompositionCode: "CMP003",
    salaryCompositionName: "Phụ cấp xăng xe và điện thoại theo cấp bậc",
    OrganizationUnitData: "Phòng Hành chính Nhân sự",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 700000,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 16,
    salaryCompositionCode: "CMP004",
    salaryCompositionName: "Hỗ trợ ăn ca ca tối",
    OrganizationUnitData: "Bộ phận Sản xuất - Ca 2 & 3",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 450000,
    source: "User",
    status: "Inactive",
  },
  {
    salaryCompositionId: 17,
    salaryCompositionCode: "CMP005",
    salaryCompositionName: "Thưởng KPI quý",
    OrganizationUnitData: "Phòng Kinh doanh – Nhóm Tư vấn",
    componentType: "Bonus",
    nature: "Positive",
    salaryValueType: "Percent",
    salaryValue: 10,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 18,
    salaryCompositionCode: "CMP006",
    salaryCompositionName: "Phụ cấp trách nhiệm quản lý",
    OrganizationUnitData: "Xưởng Đóng gói",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 1200000,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 19,
    salaryCompositionCode: "CMP007",
    salaryCompositionName: "Phạt đi muộn",
    OrganizationUnitData: "Tất cả phòng ban",
    componentType: "Penalty",
    nature: "Negative",
    salaryValueType: "Fixed",
    salaryValue: 200000,
    source: "System",
    status: "Inactive",
  },
  {
    salaryCompositionId: 20,
    salaryCompositionCode: "CMP008",
    salaryCompositionName: "Thưởng nóng hợp đồng lớn",
    OrganizationUnitData: "Phòng Kinh doanh – Doanh nghiệp",
    componentType: "Bonus",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 3000000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 21,
    salaryCompositionCode: "CMP009",
    salaryCompositionName: "Giảm trừ người phụ thuộc",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Deduction",
    nature: "Negative",
    salaryValueType: "Fixed",
    salaryValue: 4400000,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 22,
    salaryCompositionCode: "CMP010",
    salaryCompositionName: "Hỗ trợ công tác phí tỉnh",
    OrganizationUnitData: "Phòng Triển khai – Dự án B",
    componentType: "Allowance",
    nature: "Positive",
    salaryValueType: "Fixed",
    salaryValue: 800000,
    source: "User",
    status: "Active",
  },
  {
    salaryCompositionId: 23,
    salaryCompositionCode: "CMP011",
    salaryCompositionName: "Thưởng cuối năm",
    OrganizationUnitData: "Toàn công ty",
    componentType: "Bonus",
    nature: "Positive",
    salaryValueType: "Percent",
    salaryValue: 15,
    source: "System",
    status: "Active",
  },
  {
    salaryCompositionId: 24,
    salaryCompositionCode: "CMP012",
    salaryCompositionName: "Khấu trừ đồng phục",
    OrganizationUnitData: "Nhân viên thử việc",
    componentType: "Deduction",
    nature: "Negative",
    salaryValueType: "Fixed",
    salaryValue: 150000,
    source: "User",
    status: "Inactive",
  },
];
